### ISSUE TITLE
erro js com configuração de minimizar js ativo 2.4.4

### ISSUE THREAD

**Issue by redati** [pagarme/magento2#306]
```
```

Nova versão do modulo possui linhas nos arquivos js sem terminação ";" no final da linha, isso causa erros quando minimizados os arquivos js.

### Status

BUG REPORT / TASK

### Steps

1 Ative opção para minimizar arquivos JS
2 Va até a pagina de pagamento

### Expected behaviour

Fazer pedido, sem erros js

### Actual behaviour

Erro no arquivo CreditCardModel.min.js
Uncaught SyntaxError: Unexpected token 'const' (at CreditCardModel.min.js:17:46)
PaymentMethodController.min.js:6 Uncaught TypeError: CreditCardModel is not a constructor
    at PaymentMethodController.creditcardInit (PaymentMethodController.min.js:6:12)
    at PaymentMethodController.init (PaymentMethodController.min.js:2:78)
    at PagarmeCore.init (PaymentModuleBootstrap.min.js:1:431)
    at PaymentModuleBootstrap.min.js:1:534

### Environment

Ultima versão do modulo e do magento. 

### Logs / Stack trace

```
Insert your log/stack trace here
```

**Comment by hallandellon** [comment]
Aqui tenho o mesmo problema, porém não utilizo arquivos minimizados.
![pagarme1](https://github.com/pagarme/magento2/assets/3280451/49503e8a-89ac-45cc-89b5-1753f6ddc9ff)

**Comment by redati** [comment]
@hallandellon  seus arquivos estão "minimizados",  estão com ".min.js"  :)

**Comment by hallandellon** [comment]
> @hallandellon seus arquivos estão "minimizados", estão com ".min.js" :)

Verdade. Mesmo problema então. Conseguiu alguma solução?

**Comment by Cyber-Root0** [comment]
@redati @hallandellon 

Mesmo problema por aqui!! 

@RafaMelazzo por favor, consegue enviar uma correção??

**Comment by redati** [comment]
Acredito que é so colocar o ; nas linhas adicionadas na ultima atualização

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dieguitoqueiroz** [comment]
Estamos com o mesmo problema aqui. Esse bug está aberto desde janeiro. 
Quando haverá uma solução? 

Na minha loja está impedindo de renderizar o componente e os métodos de pagamento não estão aparecendo.

**Comment by fabiano-mallmann** [comment]
Bom dia pessoal!
A correção está em produção na versão 2.4.1.
