### ISSUE TITLE
Error when getting the rest api schema

### ISSUE THREAD

**Issue by robsoned** [pagarme/magento2#358]
### Steps

1. Set magento 2 to developer mode
2. Open https://{magento_url}/swagger or make a GET request to: `https://{magento_url}/rest/all/schema?services=all`

### Expected behaviour

Get the swagger API definition.

### Actual behaviour

Get the following error: `The \"KycLinkResponseInterface\" class doesn't exist and the namespace must be specified. Verify and try again.`

### Logs / Stack trace

```
#0 /var/www/magento2/src/vendor/magento/module-webapi/Model/Config/ClassReflector.php(105): Magento\\Framework\\Reflection\\TypeProcessor->register('KycLinkResponse...')\n
#1 /var/www/magento2/src/vendor/magento/module-webapi/Model/Config/ClassReflector.php(73): Magento\\Webapi\\Model\\Config\\ClassReflector->extractMethodData(Object(Laminas\\Code\\Reflection\\MethodReflection))\n
#2 /var/www/magento2/src/vendor/magento/module-webapi/Model/ServiceMetadata.php(141): Magento\\Webapi\\Model\\Config\\ClassReflector->reflectClassMethods('Pagarme\\\\Pagarme...', Array)\n
#3 /var/www/magento2/src/vendor/magento/module-webapi/Model/ServiceMetadata.php(175): Magento\\Webapi\\Model\\ServiceMetadata->initServicesMetadata()\n
#4 /var/www/magento2/src/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Webapi\\Model\\ServiceMetadata->getServicesConfig()\n
#5 /var/www/magento2/src/vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Webapi\\Model\\ServiceMetadata\\Interceptor->___callParent('getServicesConf...', Array)\n
#6 /var/www/magento2/src/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Webapi\\Model\\ServiceMetadata\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n
#7 /var/www/magento2/src/generated/code/Magento/Webapi/Model/ServiceMetadata/Interceptor.php(23): Magento\\Webapi\\Model\\ServiceMetadata\\Interceptor->___callPlugins('getServicesConf...', Array, Array)\n
#8 /var/www/magento2/src/vendor/magento/module-webapi/Model/Rest/Swagger/Generator.php(965): Magento\\Webapi\\Model\\ServiceMetadata\\Interceptor->getServicesConfig()\n
#9 /var/www/magento2/src/vendor/magento/module-webapi/Controller/Rest/SchemaRequestProcessor.php(53): Magento\\Webapi\\Model\\Rest\\Swagger\\Generator->getListOfServices()\n
#10 /var/www/magento2/src/vendor/magento/module-webapi/Controller/Rest.php(195): Magento\\Webapi\\Controller\\Rest\\SchemaRequestProcessor->process(Object(Magento\\Framework\\Webapi\\Rest\\Request\\Proxy))\n
#11 /var/www/magento2/src/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n
#12 /var/www/magento2/src/vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callParent('dispatch', Array)\n
#13 /var/www/magento2/src/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Webapi\\Controller\\Rest\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n
#14 /var/www/magento2/src/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callPlugins('dispatch', Array, Array)\n
#15 /var/www/magento2/src/vendor/magento/framework/App/Http.php(116): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n
#16 /var/www/magento2/src/vendor/magento/framework/App/Bootstrap.php(264): Magento\\Framework\\App\\Http->launch()\n
#17 /var/www/magento2/src/pub/index.php(30): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n
#18 {main}
```

**Comment by fabiano-mallmann** [comment]
@robsoned Obrigado pela contribuição.

Deploy foi realizado ontem, estou fechando a Issue.
